# Use root/example as user/password credentials

version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    container_name: mvc_express_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
